name: Build Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon --stacktrace
    
    - name: List APK files
      run: |
        echo "APK files built:"
        find app/build/outputs/apk/release -name "*.apk" -type f
    
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bitchat-android-release-apk-${{ github.ref_name }}
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
        if-no-files-found: error
    
    # Uncomment the following steps to enable APK signing
    # - name: Sign APK
    #   uses: r0adkll/sign-android-release@v1
    #   with:
    #     releaseDirectory: app/build/outputs/apk/release
    #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
    #     alias: ${{ secrets.ALIAS }}
    #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    #     keyPassword: ${{ secrets.KEY_PASSWORD }}
    
    # Uncomment the following steps to automatically attach APK to GitHub Release
    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: app/build/outputs/apk/release/*.apk
    #     tag_name: ${{ github.ref_name }}
    #     name: Release ${{ github.ref_name }}
    #     body: |
    #       Automated release of bitchat-android ${{ github.ref_name }}
    #       
    #       ## Changes
    #       - Built from commit: ${{ github.sha }}
    #       - Release APK is attached to this release
    #     draft: false
    #     prerelease: false
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}